---
script: "./script/cibuild"
gemfile: "this/does/not/exist"
rvm:
      - "1.8.7"
      - "2.0.0"
before_install:
  - gem update --system 2.1.11 # workaround for https://github.com/rubygems/rubygems/pull/763
